version: "3"
services:
  node:
    container_name: node
    build:
      context: ./
    command: npm run dev
    volumes:
      - ./src/redis:/src
    ports:
      - 3000:3000

  redis:
    container_name: redis
    image: redis:6.2.4-buster
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data:
